name: Bump Release Tag Check

permissions:
    contents: write
on:
  workflow_dispatch:

jobs:
  create-release-tag:
    permissions:
      contents: write
      pull-requests: read
    runs-on: ubuntu-latest
    steps:
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          append_to_pre_release_tag: ""
          dry_run: true

      - name: Sanitize bumped tag
        if: always()
        id: sanitize_tag
        uses: actions/github-script@v6
        with:
          script: |
            const rawTag = "${{ steps.tag_version.outputs.new_tag }}";
            const cleaned = rawTag.replace(/-[^.]+?\.\d+$/, "");
            core.info(`Raw tag: ${rawTag} â†’ Cleaned tag: ${cleaned}`);
            core.setOutput("clean", cleaned);

      - name: Create tag and release
        id: create_release
        uses: ncipollo/release-action@v1.14.0
        with:
          tag: ${{ steps.sanitize_tag.outputs.clean }}
          name: ${{ steps.sanitize_tag.outputs.clean }}
          prerelease: false
          generateReleaseNotes: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check Output Parameters
        run: |
          echo "Got tag name ${{ steps.sanitize_tag.outputs.clean }}"
          echo "Got release version ${{ steps.sanitize_tag.outputs.clean }}"
          echo "RELEASE_TAG in create-release-tag job: ${{ steps.sanitize_tag.outputs.clean }}"
          echo "Release upload URL: ${{ steps.create_release.outputs.upload_url }}"
          echo "Release output:"
          echo "${{ toJson(steps.create_release.outputs) }}"
          for key in $(echo "${{ toJson(steps.create_release.outputs) }}" | jq -r "keys_unsorted[]"); do
            value=$(echo "${{ toJson(steps.create_release.outputs) }}" | jq -r ".$key")
            echo "$key: $value"
          done

    outputs:
      LATEST_RELEASE_VERSION: ${{ steps.sanitize_tag.outputs.clean }}
      UPLOAD_URL: ${{ steps.create_release.outputs.upload_url }}
  
  build:
    runs-on: ubuntu-latest
    needs: create-release-tag
    steps:
      - name: Checkout (all tags)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Get latest tag
        id: get_latest_tag
        run: |
          git fetch --tags --force
          LATEST_TAG=$(git tag -l "v*" --sort=-version:refname | grep -E '^v[0-9]+\.[0-9]+\.[0-9]+$' | head -n 1)
          echo "Latest tag: $LATEST_TAG"
          if [[ $LATEST_TAG =~ ^v([0-9]+)\.([0-9]+)\.([0-9]+)$ ]]; then
            MAJOR=${BASH_REMATCH[1]}; MINOR=${BASH_REMATCH[2]}; PATCH=${BASH_REMATCH[3]}
          else
            echo "Tag format not recognized: $LATEST_TAG"
            exit 1
          fi
          
          NEW_MAJOR_TAG="v$((MAJOR + 1)).0.0"

          echo "new_major_tag=$NEW_MAJOR_TAG" >> $GITHUB_OUTPUT
          echo "current_major=$MAJOR" >> $GITHUB_OUTPUT
          echo "current_major ---> $MAJOR"
          echo "new_major_tag ---> $NEW_MAJOR_TAG"

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_latest_tag.outputs.new_major_tag }}
          release_name: Release ${{ steps.get_latest_tag.outputs.new_major_tag }}
          body: |
            Release created automatically by GitHub Actions.
          draft: false
          prerelease: false
